debug: false

server:
  port: 8089

auth0:
  # auth0 api identifier
  # 产生映射后，此 spring app 会成为一个 resource server 响应持有 token 的 http 请求
  audience: https://oauthDemo/api

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # auth0 提供的 domain 地址 spring 会根据这个地址找到 authorization server
          issuer-uri: https://dev-yqws8krc.us.auth0.com/
